# Generated by Django 2.1.15 on 2022-09-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mae_reportes',
            name='grafica',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1),
        ),
    ]
